### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by janblok** [Raruto/leaflet-rotate#31]
Is there a specific reason to not use the same license as Leaflet?
GPL is quite restrictive for many potencial users.

**Comment by Raruto** [comment]
Hi @janblok 

> Is there a specific reason to not use the same license as Leaflet?

My [other plugins](https://raruto.github.io/) are also based on the GPL license.

>  GPL is quite restrictive for many potencial users.

At the moment, if you are interested in any commercial use, I would advise to take advantage of much more proven open source libraries in this regard, eg:

- https://openlayers.org/
- https://maplibre.org/

BTW, I'd be happy if in an upcoming release some maintainer would [re-consider to integrate](https://github.com/Leaflet/Leaflet/issues/268#issuecomment-421838981) this feature into core..

👋 Raruto

**Comment by janblok** [comment]
The reason for asking, since its based on commits from leaflet itself as readme states, why the license change?
For any company using leaflet already, its quite hard to replace this with your suggestions.

Would you consider dual licensing if using same license as leaflet is not an option for you?

**Comment by Raruto** [comment]
> why the license change?

I could list several reasons for this, but I don't want to get boring..

> its quite hard to replace this with your suggestions.

No easy fix, but if you really think this could be a critical feature, I strongly suggest you look into sponsoring the leaflet project to have this feature included in core.

Although, meanwhile, it's been ten years since this feature was first requested https://github.com/Leaflet/Leaflet/issues/268#issuecomment-421838981 (and no organization has ever really invested anything in it..)

> Would you consider dual licensing if using same license as leaflet is not an option for you?

Who knows, maybe in the future, but keep in mind that leaflet [v2.x](https://github.com/Leaflet/Leaflet/milestone/39) is not released yet and:

- while it will be quite backwards compatible, this plugin alters substantial core code (someone will have to put their head on it..)
- by now I know Leaflet pretty well, but I don't use it that much in my day-to-day life
- very few people are able (or willing) to waste the time to improve these kind of core features (ref: [core-js](https://github.com/zloirock/core-js) epic, MIT licensed, and despite that with major contributor issues..)

👋 Raruto
