### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by ryantheleach** [Raruto/leaflet-rotate#38]
Hey @Raruto 

I notice there's been quite a bit of activity for getting the 1.9.3 release of this plugin ready, but the last release listed on github is 0.1.1

I was curious to how the 1.9.3 release was looking, and if there were any blocking issues preventing a release being cut.

**Comment by Raruto** [comment]
Hi @ryantheleach,

here on github I usually release only minor versions (eg. [v0.2.0](https://github.com/Raruto/leaflet-rotate/releases/tag/v0.2.0)), since I don't have a workflow file and I have to do it manually for other leaflet plugins as well..

Therefore, the next release on github could be **v0.3.0**.

> I notice there's been quite a bit of activity for getting the 1.9.3 release of this plugin ready

There is currently no **v1.9.3**, latest release available on npm is **v0.2.8**:

- https://www.npmjs.com/package/leaflet-rotate?activeTab=versions
- https://github.com/Raruto/leaflet-rotate/tags

> there were any blocking issues preventing a release being cut?

If someone takes care of completing these two (others PRs are welcome..):

- https://github.com/Raruto/leaflet-rotate/issues/28#issuecomment-1634517715
- https://github.com/Raruto/leaflet-rotate/issues/36

I'd be happy to release a **v0.3.0** soon.

👋 Raruto

**Comment by ryantheleach** [comment]
Sorry, I think I miscommunicated, when I mentioned 1.9.3 I was talking about versions compatible with leaflet 1.9.3
