### ISSUE TITLE
Rotating vector tiles

### ISSUE THREAD

**Issue by cubecleveland** [Raruto/leaflet-rotate#6]
Probably can not be done? but in case we are using Vector tiles, can we still have a workarounf to rotate the map. currently the vector rotates but it doesnt rerender so the map gets cut of...

**Comment by Raruto** [comment]
Hi cubecleveland,

sorry but I don't understand what you are referring to, if you are looking for help please provide a minimal example of your code (which at least describes your issue in a practical manner).

_Greetings,
Raruto_

**Comment by cubecleveland** [comment]
Absolutly,

So we are using vector tiles instead of tile Layers. We load them to  Leaflet via the mapbox-gl-leaflet plugin that aloows to show the vector tiles instead of rater tiles.
Now when applying the rotate library,  the feature 'almost works' it rotates the entire tile layer but ther are some empty spots that are renderd on the map. 
I was wondering if this library actually works with vecotr tiles or not...
LMK if that make sense, if so ill take the time and create a sandbox

**Comment by Raruto** [comment]
From what you say they could coexist, otherwise you could evaluate the use of: https://maplibre.org/ (if not mistaken it is based on "mapbox-gl-js") or working to add support within this library (at most I can give you some advices, I have no resources to develop it for you).

_Waiting for your demo,
Raruto_
