### ISSUE TITLE
north/south inversion on pixel android device

### ISSUE THREAD

**Issue by phiavogadro** [Raruto/leaflet-rotate#7]
hello for some reason n & south are almost inverted when using compass on the map. Any idea ?

thanks for this great job !

**Comment by Raruto** [comment]
Do you mean https://en.wikipedia.org/wiki/Google_Pixel ?

Sorry no idea. 🤷

**Comment by phiavogadro** [comment]
yes when i load a compass application north is ok; but when i load a map the red side of compass icon shows south, and whole map is inverted / truth. So strange....

**Comment by Raruto** [comment]
On this point, I can give you more or less the same advice as expressed here: https://github.com/Raruto/leaflet-rotate/issues/5

For example, you can debug the following function using tools provided by android:

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/map/Map.js#L68-L85

and if it helps, take a look at [this](https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/lib/debug.js) file to try to understand what is actually going wrong.

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/examples/leaflet-rotate.html#L122

As you can see, I am not a core developer and I have no more time than them to devote to this feature: https://github.com/Leaflet/Leaflet/issues/268#issuecomment-421838981

In any case, I gladly accept resolutive pull requests.

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
@phiavogadro i can't test but i guess it is related to the following: https://github.com/Raruto/leaflet-rotate/search?q=orientation

[here](https://leafletjs.com/SlavaUkraini/examples/extending/extending-3-controls.html#handlers) you will find some information you need to test (for example on how to enable / disable this leaflet `Handler`)

https://github.com/Raruto/leaflet-rotate/blob/84338b2872d9f40c4c29740a8a9356b9b6c5869a/src/map/handler/CompassBearing.js#L32

---

I don't know if it's related, but looking inside this other file I think the `_unthrottledOnDeviceOrientation` function is not defined anywhere:

https://github.com/Raruto/leaflet-rotate/blob/84338b2872d9f40c4c29740a8a9356b9b6c5869a/src/control/Rotate.js#L17

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
@heyajohnny somehow, are you able to reproduce this bug?

**Comment by heyajohnny** [comment]
@Raruto No, I can't seem to reproduce it (in the current version).
On my Xiaomi phone it works fine and in the Android emulator when choosing Pixel 3 it also works as expected.

**Comment by Raruto** [comment]
@heyajohnny just to be sure, did you test the map / icon rotation of the control in the compass mode?

That is, to work correctly, once the compass mode is activated the map should follow the rotation of the device.

**For more info:**

- [`L.Control.Rotate`](https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/control/Rotate.js#L1-L9)
- [`L.Map.CompasBearing`](https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/map/handler/CompassBearing.js#L1-L39)

https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/control/Rotate.js#L1-L9

https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/map/handler/CompassBearing.js#L1-L39

**Comment by heyajohnny** [comment]
Well, I tested it again with multiple devices and it seems to work most of the times. My conclusion is that the compass on some of the devices isn't very reliable (especially indoors). The code seems to work just as expected, but I think that the devices are a bit unreliable.

I also stumbled on pieces of code to support iOS devices with the e.webkitCompassHeading. [example](https://dev.to/orkhanjafarovr/real-compass-on-mobile-browsers-with-javascript-3emi)
In theory the iOS part should work, but I can't test it, because I don't have an iOS device...
```
_onDeviceOrientation: function(event) {
    var angle = 0;
    if(event.webkitCompassHeading) { //iOS
        angle = 360 - e.webkitCompassHeading;
    }
    else if(event.alpha)  { //android
        angle = event.alpha;
    }

    if ((event.alpha !== null || event.webkitCompassHeading !== null) && window.orientation !== undefined) {
        this._map.setBearing(Math.round(angle - window.orientation));
    }
},
```
Also the 1000 ms throttle feels very strange / laggy. A 100 ms feels way better.
 ```
 initialize: function(map) {
    this._map = map;
    this._throttled = L.Util.throttle(this._onDeviceOrientation, 100, this);
},
```
Here is a comparison of the 1000ms vs 100ms throttle

https://user-images.githubusercontent.com/20553716/215758343-1e33a6fa-5999-4a43-8cb7-290bb542b6ea.mp4


https://user-images.githubusercontent.com/20553716/215758362-82754fc3-6a73-44aa-8f77-0978b79a286c.mp4

**Comment by Raruto** [comment]
@heyajohnny related to https://github.com/Raruto/leaflet-rotate/issues/7#issuecomment-1080431410, I think that the reported problem actually refers to another plugin: [stefanocudini/leaflet-compass](https://github.com/stefanocudini/leaflet-compass):

> when i load a map the red side of compass icon shows south 

Correct me if I'm wrong, but the leaflet-rotate compass icon looks black and white, and north definitely not red.. 🧭

>  I tested it again with multiple devices and it seems to work most of the times. My conclusion is that the compass on some of the devices isn't very reliable (especially indoors). The code seems to work just as expected, but I think that the devices are a bit unreliable.

It also appears that there are different ranges on other orientation properties:

![do](https://user-images.githubusercontent.com/9614886/215810905-54806b47-9ca7-4ceb-96e0-f0c42d72a34d.png)

Ref: https://caniuse.com/?search=DeviceOrientation

> I also stumbled on pieces of code to support iOS devices with the `e.webkitCompassHeading`. [example](https://dev.to/orkhanjafarovr/real-compass-on-mobile-browsers-with-javascript-3emi)
In theory the iOS part should work, but I can't test it, because I don't have an iOS device...

Looks quite similar to current Stefano's code 😄:

## • [leaflet-compass/src/leaflet-compass.js](https://github.com/stefanocudini/leaflet-compass/blob/380097ed637251430e548c484e96ffc6b3648e21/src/leaflet-compass.js#L100-L122)

```js
  _rotateHandler: function(e) {

    var self = this, angle;

    if(!this._isActive) return false;

    if(e.webkitCompassHeading) {  //iphone
      angle = 360 - e.webkitCompassHeading;
      this._compassIphone = true;
    }
    else if(e.alpha)  {   //android
      angle = e.alpha-180;
      this._compassAndroid = true;
    }
    else {
      this._errorCompass({message: 'Orientation angle not found'});
    }

    angle = Math.round(angle);

    if(angle % this.options.angleOffset === 0)
      self.setAngle(angle);
  },
```

> Also the 1000 ms throttle feels very strange / laggy. A 100 ms feels way better.

Maybe there was a typo in the code, that throttle would appear to be defined in two different places, but as per the `L.Control.Rotate` class I don't think there is a function named `_unthrottledOnDeviceOrientation` (and I don't think it's actually added by leaflet's core `L.Map`) <-- even here I don't remember who had initially developed that class, maybe it was another fork created by [Zsolt Ero](https://github.com/hyperknot) 🤷

https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/map/handler/CompassBearing.js#L11

https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/control/Rotate.js#L19

By the way, can you submit a dedicated pull request with the changes you plan to make? So we get a better idea

👋 Raruto

**Comment by Raruto** [comment]
**PS**

> the compass on some of the devices isn't very reliable (especially indoors). The code seems to work just as expected, but I think that the devices are a bit unreliable.

In this regard, it would be interesting to add similar functions here as well:

## • [stefanocudini/leaflet-compass/src/leaflet-compass.js#L74-L76](https://github.com/stefanocudini/leaflet-compass/blob/380097ed637251430e548c484e96ffc6b3648e21/src/leaflet-compass.js#L74-L76)

```js
L.DomEvent.on(window, 'compassneedscalibration', function(e) {
  self.showAlert('Your compass needs calibrating! Wave your device in a figure-eight motion');
}, this);
```

Also as regards the activation of the compass mode it would be a good addition (also in terms of ux) to ask the user for consent before proceeding, a bit like for geolocation requests, also because apparently without an explicit consent It doesn't work on iphone at all (ref: https://github.com/stefanocudini/leaflet-compass/commit/5b2d2f9f5dc764af7209e5bc48bf9d09144f21c4)

## • [stefanocudini/leaflet-compass/src/leaflet-compass.js#L163-L180](https://github.com/stefanocudini/leaflet-compass/blob/380097ed637251430e548c484e96ffc6b3648e21/src/leaflet-compass.js#L163-L180)

```js
activate: function (isAutoActivation) {
  if (typeof(DeviceOrientationEvent) !== 'undefined' && typeof(DeviceOrientationEvent.requestPermission) === 'function') {
      /* iPhoneOS, must ask interactively */
      var that = this;
      DeviceOrientationEvent.requestPermission().then(function (permission) {
        if (permission === 'granted')       that._activate();
        else if (isAutoActivation !== true) alert('Cannot activate compass: permission ' + permission);
      }, function (reason) {
        if (isAutoActivation !== true)      alert('Error activating compass: ' + reason);
      });
    } else {
      this._activate();
    }
},
```

**Comment by heyajohnny** [comment]
@Raruto 

> Maybe there was a typo in the code, that throttle would appear to be defined in two different places, but as per the L.Control.Rotate class I don't think there is a function named _unthrottledOnDeviceOrientation (and I don't think it's actually added by leaflet's core 

You are right that there isn't any function named `_unthrottledOnDeviceOrientation` and there also isn't one in the current leaflet repo.

> In this regard, it would be interesting to add here a similar functions as well:
• [stefanocudini/leaflet-compass/src/leaflet-compass.js#L74-L76](https://github.com/stefanocudini/leaflet-compass/blob/380097ed637251430e548c484e96ffc6b3648e21/src/leaflet-compass.js#L74-L76)

I think it's obsolete. None of the current browser versions are supporting the `'compassneedscalibration'` as you can see [here](https://caniuse.com/?search=DeviceOrientation) and on this image:
![image](https://user-images.githubusercontent.com/20553716/216060139-f72850cb-3aea-498a-86d1-00f1e898e872.png)
